server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoapi
    username: root
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
